packages:
  - docs
  - packages/**
  - '!packages/nuxi'
  - '!packages/test-utils'
  - '!packages/nuxt/test/package-fixture'
  - playground
  - test/fixtures/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - oxc-resolver
  - unrs-resolver

patchedDependencies:
  changelogen: patches/changelogen.patch

publicHoistPattern:
  - '*-loader'
  - 'webpack-*'

shellEmulator: true

verifyDepsBeforeRun: install
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  '@voidzero-dev/vite-plus': latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
